spring:
  application:
    name: gateway-service-zuul
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

# 服务化，对serviceId的映射（网关的默认路由规则：http://ZUUL_HOST:ZUUL_PORT/Eureka上的serviceId/**）
#zuul:
#  routes:
#    api-a:
#      path: /user/**
#      serviceId: spring-cloud-producer