server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://gitee.com/MAXzuo/bulb          # 配置git仓库的地址
          search-paths: bulb-spring-cloud/config      # git仓库地址下的相对地址，可以配置多个，用,分割。
