spring:
  application:
    name: SofaBoot

# 日志配置
logging:
  path: ./logs
  file: ./logs/boot.log
  level:
    root: INFO
  pattern:
    console: '%d [%t] %-5p [%c] - %m%n'
    file: '%d [%t] %-5p [%c] - %m%n'

# 使用zookeeper作为注册中心
com:
  alipay:
    sofa:
      rpc:
        registry-address: zookeeper://127.0.0.1:2181