spring:
  application:
    name: SofaBoot-Provider
logging:
  path: ./logs
# 使用zookeeper作为注册中心
com:
  alipay:
    sofa:
      rpc:
        registry-address: zookeeper://127.0.0.1:2181
server:
  port: 8081