server:
  port: 8082
  tomcat:
    accept-count: 100
    max-connections: 500
    max-threads: 100
spring:
  http:
    encoding:
      enabled: true
  rabbitmq:
    host: 47.98.199.80
    port: 5672
    username: guest
    password: guest
