spring:
  application:
    name: spring-cloud-eureka
server:
  port: 8000
eureka:
  instance:
    hostname: peer1
  client:
    # 表示是否将自己注册到Eureka Server
    register-with-eureka: false
    # 表示是否从Eureka Server获取注册信息
    fetch-registry: false
    # 设置与Eureka Server交互的地址
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/