spring:
  application:
    name: spring-cloud-web-boot
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
# 熔断配置
feign:
  hystrix:
    enabled: true